version: "2"

services:
  bokeh:
    restart: always
    build:
      context: .
      args:
        BOKEH_PREFIX: /ccg
    image: discover-ccg:master
    command: ["/opt/serve-app.sh"]
    environment:
      PYTHONPATH: "/project"
      SHELL: "/bin/bash"
    ports:
      - "3249:5006"
